# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_list.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(520, 600)
        MainWindow.setMinimumSize(QtCore.QSize(520, 600))
        MainWindow.setMaximumSize(QtCore.QSize(520, 600))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/Icon32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_files_apply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_files_apply.setGeometry(QtCore.QRect(368, 528, 129, 29))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(8)
        self.btn_files_apply.setFont(font)
        self.btn_files_apply.setObjectName("btn_files_apply")
        self.lbl_index = QtWidgets.QLabel(self.centralwidget)
        self.lbl_index.setGeometry(QtCore.QRect(16, 484, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        self.lbl_index.setFont(font)
        self.lbl_index.setObjectName("lbl_index")
        self.lbl_extension = QtWidgets.QLabel(self.centralwidget)
        self.lbl_extension.setGeometry(QtCore.QRect(192, 484, 97, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        self.lbl_extension.setFont(font)
        self.lbl_extension.setObjectName("lbl_extension")
        self.btn_files_deselect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_files_deselect.setGeometry(QtCore.QRect(208, 400, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(8)
        self.btn_files_deselect.setFont(font)
        self.btn_files_deselect.setObjectName("btn_files_deselect")
        self.btn_files_select_all = QtWidgets.QPushButton(self.centralwidget)
        self.btn_files_select_all.setGeometry(QtCore.QRect(112, 400, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(8)
        self.btn_files_select_all.setFont(font)
        self.btn_files_select_all.setObjectName("btn_files_select_all")
        self.lbl_filter = QtWidgets.QLabel(self.centralwidget)
        self.lbl_filter.setGeometry(QtCore.QRect(16, 47, 97, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        self.lbl_filter.setFont(font)
        self.lbl_filter.setObjectName("lbl_filter")
        self.lbl_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name.setGeometry(QtCore.QRect(16, 440, 86, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        self.line_directory = QtWidgets.QLineEdit(self.centralwidget)
        self.line_directory.setGeometry(QtCore.QRect(112, 20, 193, 21))
        self.line_directory.setObjectName("line_directory")
        self.lbl_directory = QtWidgets.QLabel(self.centralwidget)
        self.lbl_directory.setGeometry(QtCore.QRect(16, 12, 97, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        self.lbl_directory.setFont(font)
        self.lbl_directory.setObjectName("lbl_directory")
        self.btn_dir_change = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir_change.setGeometry(QtCore.QRect(320, 20, 65, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(8)
        self.btn_dir_change.setFont(font)
        self.btn_dir_change.setObjectName("btn_dir_change")
        self.lbl_files = QtWidgets.QLabel(self.centralwidget)
        self.lbl_files.setGeometry(QtCore.QRect(16, 92, 97, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        self.lbl_files.setFont(font)
        self.lbl_files.setObjectName("lbl_files")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(112, 100, 353, 281))
        self.listWidget.setDragDropOverwriteMode(False)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setBatchSize(100)
        self.listWidget.setObjectName("listWidget")
        self.line_filter = QtWidgets.QLineEdit(self.centralwidget)
        self.line_filter.setGeometry(QtCore.QRect(112, 56, 193, 21))
        self.line_filter.setObjectName("line_filter")
        self.line_name = QtWidgets.QLineEdit(self.centralwidget)
        self.line_name.setGeometry(QtCore.QRect(112, 448, 257, 21))
        self.line_name.setObjectName("line_name")
        self.line_index = QtWidgets.QLineEdit(self.centralwidget)
        self.line_index.setGeometry(QtCore.QRect(112, 488, 65, 21))
        self.line_index.setText("")
        self.line_index.setObjectName("line_index")
        self.line_extension = QtWidgets.QLineEdit(self.centralwidget)
        self.line_extension.setGeometry(QtCore.QRect(304, 488, 65, 21))
        self.line_extension.setObjectName("line_extension")
        self.btn_dir_apply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir_apply.setGeometry(QtCore.QRect(400, 20, 65, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(8)
        self.btn_dir_apply.setFont(font)
        self.btn_dir_apply.setObjectName("btn_dir_apply")
        self.btn_filter_apply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter_apply.setGeometry(QtCore.QRect(320, 56, 65, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(8)
        self.btn_filter_apply.setFont(font)
        self.btn_filter_apply.setObjectName("btn_filter_apply")
        self.btn_files_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_files_refresh.setGeometry(QtCore.QRect(384, 400, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(8)
        self.btn_files_refresh.setFont(font)
        self.btn_files_refresh.setObjectName("btn_files_refresh")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ez Namer"))
        self.btn_files_apply.setText(_translate("MainWindow", "Re-Name Selected Files"))
        self.lbl_index.setText(_translate("MainWindow", "Start Index:"))
        self.lbl_extension.setText(_translate("MainWindow", "File Extension:"))
        self.btn_files_deselect.setText(_translate("MainWindow", "Deselect All"))
        self.btn_files_select_all.setText(_translate("MainWindow", "Select All"))
        self.lbl_filter.setText(_translate("MainWindow", "Search Filter:"))
        self.lbl_name.setText(_translate("MainWindow", "New Name:"))
        self.lbl_directory.setText(_translate("MainWindow", "Directory:"))
        self.btn_dir_change.setText(_translate("MainWindow", "Change"))
        self.lbl_files.setText(_translate("MainWindow", "Files:"))
        self.listWidget.setSortingEnabled(False)
        self.btn_dir_apply.setText(_translate("MainWindow", "Apply"))
        self.btn_filter_apply.setText(_translate("MainWindow", "Apply"))
        self.btn_files_refresh.setText(_translate("MainWindow", "Refresh List"))

